# Generated by Django 3.1.2 on 2020-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201030_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cbse',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='female',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='male',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ssc',
            new_name='degreegroup',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='transgender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='intergroup',
            field=models.BooleanField(default=False),
        ),
    ]
