# Generated by Django 3.1.2 on 2020-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201101_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='board',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='degreegroup',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='intergroup',
            field=models.CharField(max_length=25),
        ),
    ]
