# Generated by Django 3.1.2 on 2020-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201101_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='saadharno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='shouseno',
            field=models.CharField(max_length=50),
        ),
    ]
